# Raytracer Configuration File
# This file defines the default settings for the raytracer.
# The raytracer will automatically load this file on startup.

[camera]
raytrace_recurse = 5
num_camera_ray_samples = 16

[photon_mapping]
recurse_approximate_threshold = 2
photon_recurse = 3
num_photons = 202_500
photon_search_radius = 5.0
photon_search_count = 100
use_shadow_estimation = false

[materials]
shadow_distance_limit = 50.0

[objects]
rounding_error = 0.001
polymesh_epsilon = 0.000001

[sampler]
num_sets = 4

[framebuffer]
width = 512
height = 512
max_width = 2048
max_height = 2048

[cornell_box]
width = 100.0
length = 150.0
height = 90.0
